export const phrases = [
  "Bilang Mangga",
  "Cheese!",
  "Smile :)",
  "Bilang Tempe!",
  "Bilang Ubi!",
  "Senyum Dulu!",
  "Say Happy!",
  "Ciluk Baa!",
  "Wefie Time!",
  "Jangan Kedip!",
  "Say Kopi!",
  "Senyum Manis!",
  "Bilang Durian!",
  "Bilang Coklat!",
  "Say Mochi!",
  "Bilang Bakso!",
  "Jangan Gerak!",
  "Pose Kece!",
  "Bilang Pisang!",
  "Smile Like a Star!",
  "Senyum Kayak Artis!",
  "Flash On!",
  "Bilang WiLa!",
];

export const partner_map = {
  "Affection Unveiled": "Teras48",
  "Phantom of My Heart": "Teras48",
  "Teras JKT48": "Teras48",
  "About You": "48 Country",
};