name: Delete Expired Images

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  delete_images:
    runs-on: ubuntu-latest

    steps:
      - name: Call delete expired images API
        env:
          ADMIN_API_ACCESS_TOKEN: ${{ secrets.ADMIN_API_ACCESS_TOKEN }}
        run: |
          curl -X GET "https://picapop.my.id/api/delete-expired-images" \
          -H "Authorization: Bearer $ADMIN_API_ACCESS_TOKEN"
